### ISSUE TITLE
Accelerate by using GPU?

### ISSUE THREAD

**Issue by matthias-samwald** [facebookresearch/poincare-embeddings#6]
Could the code easily be adapted to run on GPU to accelerate training?

**Comment by mnick** [comment]
The code can be adapted to run on GPUs via pytorch's `.cuda()` function. However, due to the low-dimensional nature of the embeddings and the fact that the code isn't optimized for GPUs there will likely not be any performance gains from doing so.

However, 056377f906657f600ccd7739a90bffbd09b1989a includes a bugfix that will accelerate multi-core Hogwild training on CPUs significantly.
